import type { IconDefinition } from './types'

export const ICON_CATALOG: Record<string, IconDefinition> = {
  blank: {
    definitionId: 'blank',
    family: 'blank',
    valuePerColumn: 0,
    label: '[ ]',
    emoji: '⬜',
    effect: { type: 'none' },
    cost: null,
    multiCost: null,
  },
  apple: {
    definitionId: 'apple',
    family: 'apple',
    valuePerColumn: 1,
    label: 'Apple',
    emoji: '🍎',
    effect: { type: 'add_currency', currency: 'food', valuePerColumn: 1 },
    cost: { currency: 'copper', amount: 1 },
    multiCost: null,
  },
  'triple-apple': {
    definitionId: 'triple-apple',
    family: 'apple',
    valuePerColumn: 2,
    label: '2× Apple',
    emoji: '🍎',
    effect: { type: 'add_currency', currency: 'food', valuePerColumn: 2 },
    cost: { currency: 'silver', amount: 1 },
    multiCost: null,
  },
  'dozen-apple': {
    definitionId: 'dozen-apple',
    family: 'apple',
    valuePerColumn: 3,
    label: '3× Apple',
    emoji: '🍎',
    effect: { type: 'add_currency', currency: 'food', valuePerColumn: 3 },
    cost: { currency: 'gold', amount: 1 },
    multiCost: null,
  },
  copper: {
    definitionId: 'copper',
    family: 'copper',
    valuePerColumn: 1,
    label: 'Copper',
    emoji: '🟤',
    effect: { type: 'add_currency', currency: 'copper', valuePerColumn: 1 },
    cost: { currency: 'copper', amount: 1 },
    multiCost: null,
  },
  silver: {
    definitionId: 'silver',
    family: 'silver',
    valuePerColumn: 1,
    label: 'Silver',
    emoji: '⚪',
    effect: { type: 'add_currency', currency: 'silver', valuePerColumn: 1 },
    cost: { currency: 'silver', amount: 1 },
    multiCost: null,
  },
  gold: {
    definitionId: 'gold',
    family: 'gold',
    valuePerColumn: 1,
    label: 'Gold',
    emoji: '🟡',
    effect: { type: 'add_currency', currency: 'gold', valuePerColumn: 1 },
    cost: { currency: 'gold', amount: 1 },
    multiCost: null,
  },
  crown: {
    definitionId: 'crown',
    family: 'crown',
    valuePerColumn: 1,
    label: 'Crown',
    emoji: '👑',
    effect: { type: 'add_currency', currency: 'crowns', valuePerColumn: 1 },
    cost: { currency: 'gold', amount: 100 },
    multiCost: null,
  },
  air: {
    definitionId: 'air',
    family: 'air',
    valuePerColumn: 1,
    label: 'Air',
    emoji: '💨',
    effect: { type: 'add_currency', currency: 'air', valuePerColumn: 1 },
    cost: { currency: 'copper', amount: 1 },
    multiCost: null,
  },
  water: {
    definitionId: 'water',
    family: 'water',
    valuePerColumn: 1,
    label: 'Water',
    emoji: '💧',
    effect: { type: 'add_currency', currency: 'water', valuePerColumn: 1 },
    cost: { currency: 'copper', amount: 1 },
    multiCost: null,
  },
  earth: {
    definitionId: 'earth',
    family: 'earth',
    valuePerColumn: 1,
    label: 'Earth',
    emoji: '🌿',
    effect: { type: 'add_currency', currency: 'earth', valuePerColumn: 1 },
    cost: { currency: 'silver', amount: 1 },
    multiCost: null,
  },
  fire: {
    definitionId: 'fire',
    family: 'fire',
    valuePerColumn: 1,
    label: 'Fire',
    emoji: '🔥',
    effect: { type: 'add_currency', currency: 'fire', valuePerColumn: 1 },
    cost: { currency: 'gold', amount: 1 },
    multiCost: null,
  },
  energy: {
    definitionId: 'energy',
    family: 'energy',
    valuePerColumn: 1,
    label: 'Energy',
    emoji: '⚡',
    effect: { type: 'add_currency', currency: 'energy', valuePerColumn: 1 },
    cost: null,
    multiCost: [
      { currency: 'gold', amount: 1 },
      { currency: 'air', amount: 1 },
      { currency: 'water', amount: 1 },
      { currency: 'earth', amount: 1 },
      { currency: 'fire', amount: 1 },
    ],
  },
}
